name: Docker Build

env:
  RDKIT_DASH_VERSION: 2026_03_5  
  SEMVER_VERSION: 1.0.0
  BETA: false

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
      
    - name: Build with NPM
      run: |
        RDKIT_DASH_VERSION=${{ env.RDKIT_DASH_VERSION }} \
        SEMVER_VERSION=${{ env.SEMVER_VERSION }} \
        BETA=${{ env.BETA }} \
        NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
        npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: rdkit-js-dist
        path: |
          dist/
          Code/MinimalLib/dist/
